---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources: 
- ./namespace.yaml
- ./rbac.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: crossplane
    releaseName: crossplane
    repo: https://charts.crossplane.io/stable
    namespace: crossplane-system
    valuesFile: values.yaml
