default:
  project: integration-config

projects:

  integration-config:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: integration-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: integration-gitops
    description: Project for overall integration configuration
    namespace: openshift-gitops
    sourceRepos:
    - ${INFRA_GITOPS_REPO}
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:

  crossplane-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '8'
    destination:
      namespace: crossplane-system
    source:
      path: integrations/crossplane/crossplane-operator
    extraFields: |
      ignoreDifferences:
        - group: 'apps'
          jsonPointers:
            - /spec/template/spec/containers/0/env/0/valueFrom/resourceFieldRef/divisor
            - /spec/template/spec/containers/0/env/1/valueFrom/resourceFieldRef/divisor
            - /spec/template/spec/initContainers/0/env/0/valueFrom/resourceFieldRef/divisor
            - /spec/template/spec/initContainers/0/env/1/valueFrom/resourceFieldRef/divisor            
          kind: Deployment            

  crossplane-providers:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '9'
    destination:
      namespace: crossplane-system
    source:
      path: integrations/crossplane/crossplane-providers

  crossplane-provider-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: crossplane-system
    source:
      path: integrations/crossplane/crossplane-provider-config

  #crossplane-compositions:
  #  finalizers: 
  #  - resources-finalizer.argocd.argoproj.io
  #  annotations:
  #    argocd.argoproj.io/compare-options: IgnoreExtraneous
  #    argocd.argoproj.io/sync-wave: '11'
  #  destination:
  #    namespace: crossplane-system
  #  source:
  #    path: integrations/crossplane/crossplane-compositions 
                          