projects:

  managementcluster:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    - ${INFRA_GITOPS_REPO}
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:

  openshift-management:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    source:
      path: managementCluster/overlays/openshift-management

  capi-management:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '7'
    source:
      path: managementCluster/overlays/capi-management

  #rosa-capi:
  #  annotations:
  #    argocd.argoproj.io/compare-options: IgnoreExtraneous
  #    argocd.argoproj.io/sync-wave: '25'
  #  source:
  #    path: managementCluster/overlays/capi-management
                          